# These are supported funding model platforms

github: LeGitHubDeTai
custom: ["https://www.buymeacoffee.com/taistudio", "https://www.youtube.com/channel/UCZiVWB8_UNH4NLzr7XbaI8A", "https://shop.spreadshirt.fr/tai-studio/", "https://fr.tipeee.com/tai-studio"]
