version: 2.1

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  job_1:
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      - checkout
      - run:
          name: "Reporting to packtracker.io"
          command: /entrypoint.sh

workflows:
  my_workflow:
    jobs:
      - job_1
            