version: 2.1

orbs:
  shellcheck: circleci/shellcheck@x.y.z

workflows:
  check-build:
    jobs:
      - shellcheck/check
      - build-job:
          requires:
            - shellcheck/check
          filters:
            branches:
              only: main 

jobs:
  build-job:
    environment:
      - GH_TOKEN: $GH_TOKEN
      - NEW_WALLPAPERS: $NEW_WALLPAPERS

script:
  - shellcheck ./script/auto.sh