version: 2.1

jobs:
  job_1:
    executor: my-ubuntu-exec
    steps:
      - checkout
      - run:
          name: "Reporting to packtracker.io"
          command: /entrypoint.sh

workflows:
  my_workflow:
    jobs:
      - job_1
            