version: 2.1

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  autoclasser:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
        auth:
          username: TaiStudio
          password: $DOCKERHUB_PASSWORD 
    environment:
      Discord_Token: $Discord_Token
    steps:
      - checkout
      - run:
          name: Install ffmpeg
          command: sudo apt update && sudo apt install ffmpeg && ffmpeg -version
      - run:
          name: install/update pip pipenv
          command: |
            sudo python -m pip install --upgrade pip setuptools wheel
            sudo python -m pip install pipenv
      - run:
          name: update pyenv
          command: |
            # Install pyenv-update to allow addition of python 3.7.0
            git clone git://github.com/pyenv/pyenv-update.git $(pyenv root)/plugins/pyenv-update
            pyenv update
            pyenv install 3.7.0
      - run:
          name: Set Python Version
          command: pyenv global 3.7.0
      - run:
          name: "Execute all system"
          command: bash ./script/auto.sh

workflows:
  autoClasser:
    jobs:
      - autoclasser
            
