# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  build:
    shell: ./script/auto.sh
    environment:
      - GH_TOKEN: $GH_TOKEN
      - NEW_WALLPAPERS: $NEW_WALLPAPERS

workflows:
  sample: 
    jobs:
      - build
