version: 2.1

machine: true

jobs:
  job_1:
    steps:
      - checkout
      - run:
          name: "Reporting to packtracker.io"
          command: /entrypoint.sh

workflows:
  my_workflow:
    jobs:
      - job_1
            