version: 2.1

jobs:
  job_1:
    executor: my-ubuntu-exec
    steps:
      - uses: actions/checkout@master
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Chmod
        run: chmod +x ./script/auto.sh
      - name: Categories
      - run: npm run auto
        env:
          GH_TOKEN: $GH_TOKEN
          NEW_WALLPAPERS: $NEW_WALLPAPERS

workflows:
  my_workflow:
    jobs:
      - job_1