version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  autoclasser:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: TaiStudio
          password: $DOCKERHUB_PASSWORD 
    environment:
      Discord_Token: $Discord_Token
    steps:
      - checkout
      - run:
          name: Install ffmpeg
          command: sudo apt update && sudo apt install ffmpeg && ffmpeg -version
      - run:
          name: "Execute all system"
          command: bash ./script/auto.sh

workflows:
  autoClasser:
    jobs:
      - autoclasser
        filters:
          branches:
            only:
              - main
            
