version: 2.1
orbs:
    checkout: actions/checkout@master
    setup-ffmpeg: FedericoCarboni/setup-ffmpeg@v1
    win: circleci/windows@2.2.0
jobs:
  executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

  job_1:
    executor: my-ubuntu-exec
    steps:
      - run: chmod +x ./script/auto.sh
  job_2:
    executor: my-ubuntu-exec
    steps:
      - run: npm run auto
        environment:
          GH_TOKEN: $GH_TOKEN
          NEW_WALLPAPERS: $NEW_WALLPAPERS

workflows:
  my_workflow:
    jobs:
      - executor
      - job_1
      - job_2:
          requires:
            - job_1