name: Classify Wallpapers

on:
  push:
    branches: [ main ]
    
jobs:
  animeback:
    name: Categories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Chmod
        run: chmod +x ./script/auto.sh
      - name: Categories
        run: npm run auto
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NEW_WALLPAPERS: ${{ secrets.NEW_WALLPAPERS }}
