name: Classify Wallpapers

on:
  push:
    branches: [ main ]
    
jobs:
  animeback:
    runs-on: ubuntu-latest
    steps:
      - name: Chmod
        run: chmod +x ./script/auto.sh
      - name: Categories
        run: "npm start"
