name: Notification on push

on: workflow_dispatch
    
jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: LeGitHubDeTai/github-to-discord@v1.3.4
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: AnimeNews
        DISCORD_AVATAR: https://raw.githubusercontent.com/LeGitHubDeTai/AnimeBack/main/icon.png
        MESSAGE_TITLE: New Version
        MESSAGE_DESCRIPTION: AnimeBack
        MESSAGE_URL: https://github.com/LeGitHubDeTai/AnimeBack
        MESSAGE_COLOR: 5814783
